# Generated by Django 3.2.7 on 2021-10-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='post.jpg', upload_to='post_pics'),
        ),
    ]
